### ISSUE TITLE
how to use conf in docker

### ISSUE THREAD

**Issue by liyin37** [docker-library/logstash#100]
my logstash.conf is below:
```bash
input {
 redis {
        data_type => "list"
        key => "gistackinsight"
        host => "localhost"
        port => 6379
	password => 'esri@123'
        db => 2
        threads => 1
    }
}

filter {
   if "service" in [tags] {
     grok {
          match => { "message" => "%{WORD:method} %{URIPATHPARAM:request} HTTP/%{NUMBER:httpversion} %{NUMBER:response_code} %{NUMBER:response_time}" }
          #remove_field => ["message"]
     }
   }
   mutate{
     convert => ["response_code","integer","response_time","integer"]
   }
}


output {
   if "service" in [tags] {
             elasticsearch {
                     hosts => ["localhost:9200"]
                     index => "logstash-services-%{+YYYY.MM.dd}"
                     sniffing => true
                     template_overwrite => true
             }
     }
 
     if "system" in [tags] {
             elasticsearch {
                     hosts => ["localhost:9200"] 
                     index => "logstash-system-%{+YYYY.MM.dd}"
                     sniffing => true
                     template_overwrite => true
             }
     }
         stdout {
                 codec => "rubydebug"
         }
}
```

but when I run images in docker-compose
```yaml
version: "2.3"
services:
  logstash:
    image: logstash:6.8.13
    container_name: gistack-logstash
    restart: always
    env_file:
      - ./common/config/common/env
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/hosts:/etc/hosts:ro"
      - "$PWD/common/etc/logstash.conf:/opt/logstash/config/logstash.conf"
    network_mode: "host"
    command:
      [
        "/bin/sh",
        "-c",
        "/usr/share/logstash/bin/logstash -f /opt/logstash/config/logstash.conf",
      ]
   # depends_on:
   #   - elasticsearch
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
```
`docker logs -f logstash` ,it connect the `http://elasticsearch:9200` ,it use the logstash.yml in docker images，the logstash docker don't use my conf file，why，how to resolve it ?

```console
docker ps --no-trunc |grep logstash 
aed1ec0354403cd33bbc0a96788a754d137d27286669f0a68d8784751ec3c674   logstash:6.8.13        "/usr/local/bin/docker-entrypoint /bin/sh -c '/usr/share/logstash/bin/logstash -f /opt/logstash/config/logstash.conf'"   About an hour ago   Up About an hour                                 gistack-logstash
```
