### ISSUE TITLE
Provide default config file

### ISSUE THREAD

**Issue by arabold** [docker-library/logstash#16]
If this image is used as part of an automated setup, e.g. as part of an ELK stack with Docker Compose, there's no easy way to provide a custom configuration as there's no way passing command line parameters automatically when starting up the stack. The workaround is to create a new Dockerfile that's based on this one and which sets a fixed config file path.

Therefore I suggest to include a simple sample config file (pretty much empty) that can later be replaced by mounting a local volume in its place. This way we can run this Docker container without having to provide any command line parameters to configure things. 

To enable this the default logstash command would have to look something like:
`set -- logstash -f /usr/share/logstash/config/logstash.conf "$@"`
(inspired by the naming of the ElasticSearch configuration path)

**Comment by pasangsherpa** [comment]
+1

**Comment by tianon** [comment]
https://github.com/docker-library/logstash/blob/b35589d3f7d20e8b65bb87759985ae037a1a00e9/docker-entrypoint.sh#L5-L8 actually makes this trivial to do: (sample `docker-compose.yml`)

``` yaml
logstash:
  image: logstash
  command: -f /some/conf/location/logstash.conf
  volumes:
    - my-logstash.conf:/some/conf/location/logstash.conf:ro
```
