### ISSUE TITLE
Cannot output to elasticsearch container with link

### ISSUE THREAD

**Issue by goofansu** [docker-library/logstash#54]
docker-compose.yml

```
  elasticsearch:
    image: elasticsearch:latest
    ports:
      - '9200:9200'

  logstash:
    image: logstash:latest
    volumes:
      - '$PWD:/config-dir'
    command: 'logstash -f /config-dir/logstash.conf'
    links:
      - elasticsearch
    ports:
      - '5044:5044'
```

logstash.conf

```
input {
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
  }
}
```

Nothing printed at console.
